project.name=${project.name}
project.alias=${project.alias}
#GCS
bucket.dataflow.staging=${bucket.dataflow.staging}
#kafka
kafka.node.host.1=${kafka.node.host.1}
kafka.node.host.2=${kafka.node.host.2}
kafka.node.host.3=${kafka.node.host.3}
kafka.topics=${kafka.topics}