project.name=${project.name}
project.alias=${project.alias}
#GCS
bucket.dataflow.staging=${bucket.dataflow.staging}
#kafka
kafka.broker.host=${kafka.broker.host}
kafka.topics=${kafka.topics}
kafka.consumer.client.id=${kafka.consumer.client.id}
kafka.consumer.group.id=${kafka.consumer.group.id}
kafka.sasl.username=${kafka.sasl.username}
kafka.sasl.password=${kafka.sasl.password}