project.name=${PROJECT_NAME}
project.alias=prd
#GCS
bucket.dataflow.staging=${BUCKET_DATAFLOW_STAGING}
#kafka
kafka.broker.host=${KAFKA_BROKER_HOST}
kafka.topics=test_df
kafka.consumer.client.id=gcp-dataflow-client-prd
kafka.consumer.group.id=gcp-dataflow-group-prd
kafka.sasl.username=${KAFKA_SASL_USERNAME}
kafka.sasl.password=${KAFKA_SASL_PASSWORD}