project.name=<project>
project.alias=dev
#GCS
bucket.dataflow.staging=<staging_bucket>
#kafka
kafka.node.host.1=localhost
kafka.node.host.2=localhost
kafka.node.host.3=localhost
kafka.topics=test-topic