project.name=dataflow-test-290e
project.alias=dev
#GCS
bucket.dataflow.staging=dataflow-staging-dataflow-test-290e
#kafka
kafka.node.host.1=86.94.171.163
kafka.node.host.2=86.94.171.163
kafka.node.host.3=86.94.171.163
kafka.topics=test-topic