project.name=dataflow-test-290e
project.alias=dev
#GCS
bucket.dataflow.staging=dataflow-staging-dataflow-test-290e
#kafka
kafka.node.host.1=pkc-ewzgj.europe-west4.gcp.confluent.cloud
kafka.node.host.2=pkc-ewzgj.europe-west4.gcp.confluent.cloud
kafka.node.host.3=pkc-ewzgj.europe-west4.gcp.confluent.cloud
kafka.topics=test_df