name: Code and Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
      - name: Build kafka-dataflow
        run: mvn -B -f kafka-dataflow/pom.xml install
      - name: Build kafka-example-client
        run: mvn -B -f kafka-example-client/pom.xml install
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Gitleaks to scan for secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "detect --source=. --log-opts=--all --exit-code 1"
